Gust.Core/Controllers/AdminController.cs
using Gust.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gust.Core.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;

        public AdminController(ILogger<AdminController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gust.Core/Controllers/EquipoController.cs
using Gust.Core.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Gust.Core.Data;
using Gust.Core.Areas.Identity.Data.Forms;
using Microsoft.AspNetCore.Identity;
using Gust.Core.Areas.Identity.Data;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace Gust.Core.Controllers
{
    public class EquipoController : Controller
    {
        private readonly ILogger<EquipoController> _logger;
        private readonly GustCoreContext _context;
        private readonly UserManager<GustCoreUser> _userManager;

        public EquipoController(
            ILogger<EquipoController> logger,
            GustCoreContext context,
            UserManager<GustCoreUser> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }

        //Metodos de Navegacion
        public IActionResult Inventario()
        {
            return View();
        }

        public IActionResult Registrar()
        {
            return View();
        }

        public IActionResult Consultar()
        {
            return View();
        }

        public IActionResult Eliminar()
        {
            return View();
        }

        public IActionResult Actualizar()
        {
            return View();
        }


        // Metodo para registrar un equipo
        [HttpPost]
        public string PostRegistrarEquipo(string data)
        {
            
            if (data == null)
            {
                return JsonConvert.SerializeObject(null);
            }

            try
            {
                var registro = JsonConvert.DeserializeObject<Equipo>(data);
                if (registro == null)
                {
                    throw new Exception("Null Object");
                }

                _context.Equipo.Add(registro);
                _context.SaveChanges();

                return JsonConvert.SerializeObject(registro);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        public string PostActualizarEquipo(string data)
        {

            if (data == null)
            {
                return JsonConvert.SerializeObject(null);
            }

            try
            {
                var registro = JsonConvert.DeserializeObject<Equipo>(data);
                if (registro == null)
                {
                    throw new Exception("Null Object");
                }

                _context.Equipo.Update(registro);
                _context.SaveChanges();

                return JsonConvert.SerializeObject(registro);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        [HttpGet]
        public string GetEquiposInventario()
        {
            try
            {
                var equipos = _context.Equipo
                    .Select(x => new { x.Id, x.NombreEquipo, x.Modelo })
                    .ToList();

                return JsonConvert.SerializeObject(equipos);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        
        public string GetEquipoByCodigo (string data)
        {
            if (data == null)
            {
                return JsonConvert.SerializeObject(null);
            }

            try
            {
                var registro = JsonConvert.DeserializeObject<Equipo>(data);
                if (registro == null)
                {
                    throw new Exception("Null Object");
                }

                var equipoConsultado = _context.Equipo
                    .Where(x => x.CodigoBienesPatrimoniales == registro.CodigoBienesPatrimoniales)
                    .Select(x => new { x.Id, x.CodigoBienesPatrimoniales, x.Identificador, x.NombreEquipo, x.Modelo, x.VidaUtilEstimada, x.FechaCompra, x.FechaRegistro, x.Descripcion, x.LaboratorioId, x.Activo })
                    .ToList();

                return JsonConvert.SerializeObject(equipoConsultado);

            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        [HttpGet]
        public string GetLaboratorios()
        {
            try
            {
                var laboratorios = _context.Laboratorio
                    .Select(x => new { x.Id, x.Codigo })
                    .ToList();

                return JsonConvert.SerializeObject(laboratorios);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }
    }
}

Gust.Core/Controllers/FormsController.cs
using Gust.Core.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Gust.Core.Data;
using Gust.Core.Areas.Identity.Data.Forms;
using Microsoft.AspNetCore.Identity;
using Gust.Core.Areas.Identity.Data;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using Gust.Core.Areas.Identity.Data.Tasks;
using Microsoft.Win32;

namespace Gust.Core.Controllers
{
    [Authorize(Roles = "Administrador, Tec")]
    public class FormsController : Controller
    {
        private readonly ILogger<FormsController> _logger;
        private readonly GustCoreContext _context;
        private readonly UserManager<GustCoreUser> _userManager;

        public FormsController(
            ILogger<FormsController> logger, 
            GustCoreContext context,
            UserManager<GustCoreUser> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }
        
        // Metodo Con mismo nombre que la vista
        public IActionResult Prestamo()
        {
            return View();
        }
        public IActionResult PrestamoLab()
        {
            return View();
        }
        public IActionResult Devolucion()
        {
            return View();
        }
        public IActionResult DevolucionLab()
        {
            return View();
        }

        public IActionResult Tareas()
        {
            return View();
        }

        public IActionResult RegistrarTarea()
        {
            return View();
        }

        public IActionResult ActualizarTarea()
        {
            return View();
        }


        [HttpGet]
        public string GetEquipos()
        {
            try
            {
                var equipos = _context.Equipo
                    .Where(x => x.Activo && x.Prestamos.Where(y => y.FechaDevolucion == null).Count() == 0)
                    .Select(x => new { x.Id, x.NombreEquipo })
                    .ToList();
                    
                return JsonConvert.SerializeObject(equipos);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        public string GetEquiposInventario()
        {
            try
            {
                var equipos = _context.Equipo
                    .Select(x => new { x.Id, x.NombreEquipo, x.CodigoBienesPatrimoniales})
                    .ToList();

                return JsonConvert.SerializeObject(equipos);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        // Metodo para mostrar tareas
        [HttpGet]
        public string GetTareas()
        {
            try
            {
                var tareas = _context.Tarea
                    .Include(x => x.PersonaEncargada)
                    .Where(x => x.EstadoTarea == "En progreso" || x.EstadoTarea == "Sin iniciar")
                    .Select(x => new { x.Id, x.Nombre, x.Especificacion, x.FechaAsignacion, x.FechaFinalizacion, x.EstadoTarea, x.PersonaEncargada.UserName })
                    .ToList();

                return JsonConvert.SerializeObject(tareas);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        public string GetUsuarios()
        {
            try
            {
                var user = _context.Users
                    .Select(x => new { x.Id, x.UserName })
                    .ToList();

                return JsonConvert.SerializeObject(user);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        public string GetTareasActualizar()
        {
            try
            {
                var tareas = _context.Tarea
                    .Select(x => new { x.Id,x.Nombre, x.FechaAsignacion})
                    .ToList(); 

                return JsonConvert.SerializeObject(tareas);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

       

        public string GetTareaByCodigo(string data)
        {
            if (data == null)
            {
                return JsonConvert.SerializeObject(null);
            }

            try
            {
                var tarea = JsonConvert.DeserializeObject<Tarea>(data);
                if (tarea == null)
                {
                    throw new Exception("Null Object");
                }

                var tareaConsultada = _context.Tarea
                    .Where(x => x.Id == tarea.Id)
                    .Select(x => new { x.Id, x.Nombre, x.Especificacion, x.FechaAsignacion, x.FechaFinalizacion, x.EstadoTarea, x.PersonaEncargadaId})
                    .ToList();

                return JsonConvert.SerializeObject(tareaConsultada);

            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        // Metodo para crear tarea
        [HttpPost]
        public string SubmitTarea(string data)
        {
            if (data == null)
            {
                return JsonConvert.SerializeObject(null);
            }


            try
            {
                var tarea = JsonConvert.DeserializeObject<Tarea>(data);
                if (tarea == null)
                {
                    throw new Exception("Null Object");
                }

                tarea.PersonaEncargadaId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                

                _context.Tarea.Add(tarea);
                _context.SaveChanges();

                return JsonConvert.SerializeObject(tarea);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

       

        // Metodo para modificar tarea 

        public string PostActualizarTarea(string data)
        {
            
            if (data == null)
            {
                return JsonConvert.SerializeObject(null);
            }

            try
            {
                
                var tarea = JsonConvert.DeserializeObject<Tarea>(data);
                if (tarea == null)
                {
                    throw new Exception("Null Object");
                }

                _context.Tarea.Update(tarea);
                _context.SaveChanges();

                return JsonConvert.SerializeObject(tarea);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }



        public string GetLaboratorios()
        {
            try
            {
                var laboratorios = _context.Laboratorio
                    .Where(x => x.Activo && x.Reservas.Where(y => y.FechaDevolucion == null).Count() == 0)
                    .Select(x => new { x.Id, x.Codigo })
                    .ToList();

                return JsonConvert.SerializeObject(laboratorios);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        [HttpGet]
        public string GetEquiposPrestados()
        {
            try
            {
                var prestamos = _context.Prestamo
                    .Where(x => x.FechaDevolucion == null)
                    .Include(x => x.Equipo)
                    .Select(x => new { x.Id, x.Equipo.NombreEquipo, x.NombrePersona })
                    .ToList();

                return JsonConvert.SerializeObject(prestamos);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        [HttpGet]
        public string GetSalones()
        {
            try
            {
                var reservas = _context.Reserva
                    .Where(x => x.FechaDevolucion == null)
                    .Include(x => x.Laboratorio)
                    .Select(x => new { x.Id, x.Laboratorio.Codigo, x.NombrePersona })
                    .ToList();

                return JsonConvert.SerializeObject(reservas);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        public string GetReservas()
        {
            try
            {
                var reservas = _context.Reserva
                    .Include(x => x.Laboratorio)
                    .Select(x => new { x.Id,x.FechaInicio,x.Descripcion ,x.NombrePersona,x.CedulaPersona, x.Laboratorio.Codigo, x.Duracion ,x.UsuarioEntrega.UserName , x.FechaDevolucion, x.UsuarioRecibe.Email })
                    .ToList();

                return JsonConvert.SerializeObject(reservas);
            }
            catch (Exception e)
            {
                _logger.LogError("Error: {e}", e.Message);
                return JsonConvert.SerializeObject(null);
            }
        }

        // Metodo para insertar formulario
        [HttpPost]
        public string SubmitPrestamo(string data)
        {

Gust.Core/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Gust.Core.Areas.Identity.Data

@inject SignInManager<GustCoreUser> SignInManager
@inject UserManager<GustCoreUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Gestión de la Unidad de Soporte Técnico de la FISC</title>
    <link rel="shortcut icon" type="image/png" href="~/GUST.png"/>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gust.Core.styles.css" asp-append-version="true" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema GUST</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) )
                        {
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Soporte Técnico
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="Prestamo">Préstamo de Equipo</a>
                                                </li>
                                            }
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="Devolucion">Devolución de Equipo</a>
                                                </li>
                                            }
                                            <div class="dropdown-divider"></div>
                                            @if (SignInManager.IsSignedIn(User))
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="PrestamoLab">Préstamo de Laboratorio</a>
                                                </li>
                                            }
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="DevolucionLab">Devolución de Laboratorio</a>
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                </ul>
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" asp-controller="Equipo" asp-action="Inventario" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Inventario
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                            @if (SignInManager.IsSignedIn(User))
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Equipo" asp-action="Inventario">Inventario de Equipos</a>
                                                </li>
                                            }
                                            <div class="dropdown-divider"></div>
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Equipo" asp-action="Registrar">Registro de Equipo</a>
                                                </li>
                                            }
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Equipo" asp-action="Consultar">Consulta de Equipo</a>
                                                </li>
                                            }
                                            @if (SignInManager.IsSignedIn(User))
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Equipo" asp-action="Actualizar">Actualización de Equipo</a>
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                </ul>

                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" asp-controller="Forms" asp-action="Tareas" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Tareas
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="Tareas">Tareas</a>
                                                </li>
                                            }
                                           
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="RegistrarTarea">Crear Tarea</a>
                                                </li>
                                            }
                                            @if (SignInManager.IsSignedIn(User) )
                                            {
                                                <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="ActualizarTarea">Modificar Tarea</a>
                                                </li>
                                            }
                                           
                                        </ul>
                                    </li>
                            </ul>

                          
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrador")){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                      
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Universidad Tecnológica de Panamá 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>